"""Tests for ContractVisualizer."""
import pytest
from agent_contracts import (
    NodeRegistry,
    NodeContract,
    TriggerCondition,
    ModularNode,
    NodeInputs,
    NodeOutputs,
    ContractVisualizer,
)


# =============================================================================
# Test Fixtures
# =============================================================================

class InterviewerNode(ModularNode):
    """Mock interviewer node."""
    CONTRACT = NodeContract(
        name="interviewer",
        description="Conducts user interview",
        reads=["request", "shopping"],
        writes=["shopping", "response"],
        supervisor="shopping",
        requires_llm=True,
        trigger_conditions=[
            TriggerCondition(
                priority=10,
                when={"request.action": "interview"},
                llm_hint="Continue interview when action is interview",
            ),
        ],
    )
    
    async def execute(self, inputs: NodeInputs) -> NodeOutputs:
        return NodeOutputs(response={})


class LikeHandlerNode(ModularNode):
    """Mock like handler node."""
    CONTRACT = NodeContract(
        name="like_handler",
        description="Handles product likes",
        reads=["request", "card", "shopping"],
        writes=["card", "shopping"],
        supervisor="shopping",
        trigger_conditions=[
            TriggerCondition(
                priority=100,
                when={"request.action": "like"},
                llm_hint="Handle LIKE action",
            ),
        ],
    )
    
    async def execute(self, inputs: NodeInputs) -> NodeOutputs:
        return NodeOutputs(card={})


class CardCreatorNode(ModularNode):
    """Mock card creator node."""
    CONTRACT = NodeContract(
        name="card_creator",
        description="Creates the final card",
        reads=["card"],
        writes=["response"],
        supervisor="card",
        requires_llm=True,
        is_terminal=True,
    )
    
    async def execute(self, inputs: NodeInputs) -> NodeOutputs:
        return NodeOutputs(response={})


@pytest.fixture
def registry() -> NodeRegistry:
    """Create registry with test nodes."""
    reg = NodeRegistry(valid_slices={"request", "response", "shopping", "card", "_internal"})
    reg.register(InterviewerNode)
    reg.register(LikeHandlerNode)
    reg.register(CardCreatorNode)
    return reg


@pytest.fixture
def visualizer(registry: NodeRegistry) -> ContractVisualizer:
    """Create visualizer instance."""
    return ContractVisualizer(registry)


# =============================================================================
# Test Cases
# =============================================================================

class TestContractVisualizer:
    """Tests for ContractVisualizer."""
    
    def test_generate_architecture_doc(self, visualizer: ContractVisualizer):
        """Test full document generation."""
        doc = visualizer.generate_architecture_doc()
        
        # Check header
        assert "# 🏗️ Agent Architecture" in doc
        
        # Check all major sections exist
        assert "## 📦 State Slices" in doc
        assert "## 🎯 System Hierarchy" in doc
        assert "## ⚡ Trigger Hierarchy" in doc
        assert "## 📚 Nodes Reference" in doc
        
        # Check footer
        assert "Generated by `agent-contracts`" in doc
    
    def test_state_slices_section(self, visualizer: ContractVisualizer):
        """Test state slices documentation."""
        section = visualizer.generate_state_slices_section()
        
        # Check slices are listed
        assert "`request`" in section
        assert "`shopping`" in section
        assert "`card`" in section
        assert "`response`" in section
        
        # Check table structure
        assert "| Slice |" in section
        assert "Read By" in section
        assert "Written By" in section
        
        # Check Mermaid ER diagram
        assert "```mermaid" in section
        assert "erDiagram" in section
    
    def test_hierarchy_diagram(self, visualizer: ContractVisualizer):
        """Test supervisor hierarchy diagram."""
        section = visualizer.generate_hierarchy_diagram()
        
        # Check Mermaid flowchart
        assert "```mermaid" in section
        assert "flowchart TB" in section
        
        # Check supervisors as subgraphs
        assert "Shopping" in section or "shopping" in section
        assert "Card" in section or "card" in section
        
        # Check nodes are included
        assert "interviewer" in section
        assert "like_handler" in section
        assert "card_creator" in section
        
        # Check terminal styling
        assert "classDef terminal" in section
    
    def test_trigger_hierarchy(self, visualizer: ContractVisualizer):
        """Test trigger hierarchy documentation."""
        section = visualizer.generate_trigger_hierarchy()
        
        # Check priority indicators
        assert "🔴" in section  # High priority (100)
        assert "🟢" in section  # Low priority (10)
        
        # Check table structure
        assert "| Priority |" in section
        assert "| Node |" in section
        
        # Check nodes are listed
        assert "`like_handler`" in section
        assert "`interviewer`" in section
        
        # Check conditions are shown
        assert "request.action" in section
    
    def test_nodes_reference(self, visualizer: ContractVisualizer):
        """Test nodes reference table."""
        section = visualizer.generate_nodes_reference()
        
        # Check table headers
        assert "| Node |" in section
        assert "| Supervisor |" in section
        assert "| Reads |" in section
        assert "| Writes |" in section
        assert "| LLM |" in section
        assert "| Terminal |" in section
        
        # Check LLM indicators
        assert "✅" in section  # LLM required
        
        # Check terminal indicator
        assert "🔚" in section  # Terminal node
        
        # Check legend
        assert "<details>" in section
        assert "Legend" in section
    
    def test_empty_registry(self):
        """Test with empty registry."""
        reg = NodeRegistry()
        viz = ContractVisualizer(reg)
        
        doc = viz.generate_architecture_doc()
        
        # Should still have header and footer
        assert "# 🏗️ Agent Architecture" in doc
        assert "Generated by" in doc
    
    def test_dataflow_diagram(self, visualizer: ContractVisualizer):
        """Test data flow diagram generation."""
        section = visualizer.generate_dataflow_diagram()
        
        # Check Mermaid flowchart
        assert "```mermaid" in section
        assert "flowchart LR" in section
        
        # Check nodes are included
        assert "interviewer" in section
        assert "like_handler" in section
        
        # Check edge labels contain slice names
        assert "shopping" in section or "card" in section


class TestPriorityIcons:
    """Tests for priority icon assignment."""
    
    def test_priority_icons(self, visualizer: ContractVisualizer):
        """Test priority icon thresholds."""
        assert visualizer._get_priority_icon(100) == "🔴"
        assert visualizer._get_priority_icon(150) == "🔴"
        assert visualizer._get_priority_icon(50) == "🟡"
        assert visualizer._get_priority_icon(75) == "🟡"
        assert visualizer._get_priority_icon(10) == "🟢"
        assert visualizer._get_priority_icon(25) == "🟢"
        assert visualizer._get_priority_icon(5) == "⚪"
        assert visualizer._get_priority_icon(-1) == "⚪"


class TestNodeIcons:
    """Tests for node icon assignment."""
    
    def test_terminal_icon(self, registry: NodeRegistry, visualizer: ContractVisualizer):
        """Test terminal node gets terminal icon."""
        contract = registry.get_contract("card_creator")
        icon = visualizer._get_node_icon(contract)
        assert icon == "🔚"
    
    def test_llm_icon(self, registry: NodeRegistry, visualizer: ContractVisualizer):
        """Test LLM node gets robot icon."""
        contract = registry.get_contract("interviewer")
        icon = visualizer._get_node_icon(contract)
        # LLM nodes get robot icon (checked before name patterns)
        assert icon == "🤖"
    
    def test_like_icon(self, registry: NodeRegistry, visualizer: ContractVisualizer):
        """Test like handler gets heart icon."""
        contract = registry.get_contract("like_handler")
        icon = visualizer._get_node_icon(contract)
        assert icon == "❤️"
